### PR TITLE
Storage v1

### LINKED ISSUE #4: As a user, I can save my data in a file
... so that I can import my saved data to my new computer.

### PR DESCRIPTION
**Pull request by Nahoyhp**
Read, Write and Archive for ExerciseBook is completed.

### CODE REVIEW

**Review by aaronlwm — COMMENTED** [review]
Tested locally, default test cases passed.

Issue when running TestDriver.java locally:


12:14:17 PM: Executing task 'TestDriver.main()'...

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :TestDriver.main()
Exceptions

BUILD SUCCESSFUL in 0s
3 actionable tasks: 1 executed, 2 up-to-date
Oct 07, 2020 12:14:18 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: Json file data\testing.json not found
12:14:18 PM: Task execution finished 'TestDriver.main()'.

Data stored in the /data/ won't be included in commit (listed in gitignore).

Perhaps you can move them to src/test/data instead?
Also, I think the TestDriver class should belong somewhere in src/test instead. Classes in src/main are used in running the app itself.

**Comment by Nahoyhp** [comment]
This is not my final copy yet. Just want to run the above tests to see where I need to help.

**Comment by Liu-2001** [comment]
Tested locally. All storage related tests passed. 

For TestDriver.java, if I run it multiple times, the data will be stored repeatedly into testingForExercise.json. Is that the desired outcome or should you first clear the file and then store the exercise book? (not sure about this)

Otherwise LGTM.

**Comment by Nahoyhp** [comment]
The TestDriver is created to ensure that I can read and write from the data. 
 The reason for the repeats is because it reads all the items in the storage, can't realize that items with same name and date are the same (cuz i am using stubs) and just add items at the end of the list.
The TestDriver also includes reading from past records and add the same set of Exercise at the end.

**Pull request merged**
